### ISSUE TITLE
usernames work perfect but how can we use user_ids?

### ISSUE THREAD

**Issue by iCrack3x** [MmdUnion/instagram-scraper#1]
I would like to use user_ids instead of usernames

**Comment by MmdUnion** [comment]
Thank you for your suggestion! Currently, this feature do not supported by this project
[Welcome contribution](https://github.com/MmdUnion/instagram-scraper/pulls)

**Comment by MmdUnion** [comment]
https://github.com/MmdUnion/instagram-scraper/commit/50ff741ce1ef3b43ba6d3ba51594fb3773bd8b8d

**Comment by MmdUnion** [comment]
https://github.com/MmdUnion/instagram-scraper/commit/50ff741ce1ef3b43ba6d3ba51594fb3773bd8b8d
