### ISSUE TITLE
not open the UI 

### ISSUE THREAD

**Issue by nf24eg** [MmdUnion/instagram-scraper#2]
after installing the requirments and run.py that's what I get, and nothing happen since then

←[32mINFO←[0m:     Started server process [←[36m16528←[0m]
←[32mINFO←[0m:     Started server process [←[36m16528←[0m]
←[32mINFO←[0m:     Waiting for application startup.
←[32mINFO←[0m:     Waiting for application startup.
←[32mINFO←[0m:     Application startup complete.
←[32mINFO←[0m:     Application startup complete.
←[32mINFO←[0m:     Uvicorn running on ←[1mhttp://127.0.0.1:8000←[0m (Press CTRL+C to quit)
←[32mINFO←[0m:     Uvicorn running on ←[1mhttp://127.0.0.1:8000←[0m (Press CTRL+C to quit)

**Comment by MmdUnion** [comment]
Please provide additional information, including a screenshot of the error displayed in browser when accessing `http://127.0.0.1:8000/redoc`, as well as a screenshot of the CMD/terminal where the project was executed.
